fix(apd-schema): Rename migration V032 (#359)
* fix(apd-schema): Rename migration V032.

FlywayException: Found more than one migration with version 032

* Bump to version 0.21.0-1-fix-v032-migration-schema [skip ci]

---------

Co-authored-by: pagopa-github-bot <github-bot@pagopa.it>